name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip and requests
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install requests

      - name: Set environment variables 
        run: | 
          export AMENT_CURRENT_PREFIX=/opt/ros/foxy
          export COLCON_PYTHON_EXECUTABLE=/usr/bin/python3

      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

      - name: Install dependencies 
        run: | 
          apt-get update 
          apt-get install -y python3-pip 
          pip3 install requests beautifulsoup4    

